version: '3.0'

services:
    elasticsearch:
        # Elasticsearch
        build: ./elasticsearch
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
            - cluster.name=elasticsearch
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - 9200:9200
            - 9300:9300
        volumes:
            - ./elasticsearch:/usr/share/elasticsearch/data
        networks:
            - esnet

    mysql:
        # MySQL（ユーザ，閲覧履歴）
        image: mysql:5.7
        container_name: mysql
        platform: linux/x86_64
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app
            MYSQL_USER: test
            MYSQL_PASSWORD: test
            TZ: 'Asia/Tokyo'
        volumes:
            - ./db/data:/var/lib/mysql 
            - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./db/sql:/docker-entrypoint-initdb.d
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        networks:
            - esnet
            
    python3:
        # Flask（+推薦システム）
        build: ./backend
        container_name: python3
        links:
            - elasticsearch
            - mysql
        ports:
            - "5000:5000"
            - "80:80"
            - "8022:22"
        tty: true
        environment:
            TZ: Asia/Tokyo
        volumes:
            - .:/projects
        networks:
            - esnet

networks:
    esnet:
